{% set name = "mmsegmentation" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mmsegmentation-{{ version }}.tar.gz
  sha256: 35dbd8089fd1c2baa467d3b7c2e1b197043f4f955ad5de8005170eee469102ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - matplotlib-base
    - mmcv <2.2.0  # https://github.com/open-mmlab/mmsegmentation/issues/3729
    - numpy
    - packaging
    - prettytable
    - py-opencv
    - python >={{ python_min }}
    - scipy

test:
  imports:
    - mmseg
  source_files:
    - tests
  commands:
    # - pip check  # disabled because mmengine on conda-forge is mmengine-lite
    - python -m pytest ./tests/
    - python -c "import mmseg; print(mmseg.__version__)"
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: http://github.com/open-mmlab/mmsegmentation
  summary: Open MMLab Semantic Segmentation Toolbox and Benchmark
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://mmsegmentation.readthedocs.io

extra:
  recipe-maintainers:
    - weiji14
